### ISSUE TITLE
Key recovery doesn't work with all combinations/orders of shares

### ISSUE THREAD

**Issue by ChakshuGupta** [ginsburgnm/pyseltongue#1]
I was working with a 3 of 5 split of shares. The only combination of shares that produces the correct key was 0,1,2. Any other order or combination produced different results.

**Comment by ginsburgnm** [comment]
@ChakshuGupta Did you close this because you got it working? or are you working on it in a separate repository now?

**Comment by ChakshuGupta** [comment]
I got it working. That's why closed it.
