### ISSUE TITLE
Got a bug 

### ISSUE THREAD

**Issue by hasanseam** [ginsburgnm/pyseltongue#5]
Hi,

Thank you publishing for your great library for secret sharing.

When I using  PlaintextToHexSecretSharer class I got a bug.

You can check this by using this key = '0B4A30EEFEBA6783EA68F79AD5DC85E4DDCD83D4'

My result is following 

Mykey = 0B4A30EEFEBA6783EA68F79AD5DC85E4DDCD83D4

Shares = ['1-bcea3e58f116fb8c28151ce22bb6a45a35f610119e0e60211bb6d658258f06c2360b207e91f17da2', '2-79d47cb1e22df7151d2edcd9b8751be52c2999dcba6c258d0e7eea2fc30674775176a63bbf7615b9', '3-36bebb0ad344f29e12489cd145339370225d23a7d6c9eaf90146fe07607de22c6ce22bf8ecfaadd0', '4-f3a8f963c45bee2707625cc8d1f20afb1890ad72f327b064f40f11defdf54fe1884db1b61a7f4602', '5-b09337bcb572e9affc7c1cc05eb082860ec4373e0f8575d0e6d725b69b6cbd96a3b937734803de19']
AfterRecombinig = B4A30EEFEBA6783EA68F79AD5DC85E4DDCD83D4

After recombining 0 doesn't show up

**Comment by ginsburgnm** [comment]
Confirmed; It results from `charset_to_int` from utilitybelt. I'll see if I can do anything about that.

**Comment by ginsburgnm** [comment]
@hasanseam I've drafted a new release, this should fix your issue. I have also updated unit tests to include leading zeros there; thank you for bringing this to my attention, I hope this helps you out.
